resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: containerdaysjp/pr

resources:
- name: showks-canvas-pr
  type: pull-request
  check_every: 1m
  webhook_token: ((github_webhook_token))
  source:
    repo: containerdaysjp/showks-canvas-USERNAME
    access_token: ((github_access_token))
    private_key: ((github_key))

- name: showks-canvas
  type: git
  source:
    uri: https://github.com/containerdaysjp/showks-canvas

jobs:
- name: test
  plan:
  - get: showks-canvas-pr
    trigger: true
    version: every
  - put: showks-canvas-pr
    params:
      path: showks-canvas-pr
      status: pending
  - get: showks-canvas
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: containerdaysjp/ruby
          tag: "2.5"
      inputs:
        - name: showks-canvas-pr
        - name: showks-canvas
      outputs:
        - name: messages
      run:
        path: /bin/bash
        args:
          - -xce
          - |
            echo "Sorry, something went wrong." > messages/failed
            cd showks-canvas-pr
  
            # ARGS
            AUTH_TOKEN=$AUTH_TOKEN
            PR_NUM=`cat .git/id`
            REPO=showks-canvas-USERNAME
            URL="https://api.github.com/repos/containerdaysjp/${REPO}/pulls/${PR_NUM}"
            CURL="curl -s -H \"Authorization: token ${AUTH_TOKEN}\""
  
            # Where is this PR from and what is branch name?
            PR_FROM_BRANCH=$(${CURL} ${URL} | jq -r '.head.ref, .head.repo.full_name')
            PR_BRANCH=$(echo $PR_FROM_BRANCH | cut -d " " -f 1)
            PR_REMOTE=$(echo $PR_FROM_BRANCH | cut -d " " -f 2)
  
            # Check branch name
            if [ `git config --get pullrequest.branch` != "staging" -a `git config --get pullrequest.basebranch` == "master" ]
            then
              echo "You cannot send PR to master branch directly. Send staging branch first." > ../messages/failed
              exit 1
            fi
  
            # Check github repo
            if [ "${PR_REMOTE}" != "containerdaysjp/${REPO}" ]; then
                echo "You cannot send PR from forked repository. Please send from same repository" > ../messages/failed
                exit 1
            fi
  
            cd ../
            cat << EOS > checker.rb
            require 'json'
  
            json = ""
            File.open(ARGV[0], "r") do |f|
              begin
                json = JSON.parse(f.read)
              rescue
                p "invalid json format"
                exit(false)
              end
            end
            if !json["userName"] || !json["gitHubId"]
              p "userName and gitHubId are required."
              exit(false)
            end
            exit
            EOS
  
            echo "The file src/data/author.json looks invalid." > messages/failed
            ruby checker.rb showks-canvas-pr/src/data/author.json
  
            echo "Merge pull request" > messages/merge
            echo "LGTM!" > messages/lgtm
            echo "You can modify src/data/author.json only" > messages/failed
            diff -q -r -x ".git" showks-canvas showks-canvas-pr | grep -v "src/data/author.json"  | test $(wc -l) == 0
    on_failure:
      put: showks-canvas-pr
      params:
        path: showks-canvas-pr
        status: failure
        comment: messages/failed
    on_success:
      put: showks-canvas-pr
      params:
        path: showks-canvas-pr
        status: success
        comment: messages/lgtm
        merge:
          method: merge
          commit_msg: messages/merge

